apiVersion: v1
kind: Namespace
metadata:
  name: blog-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: blog-namespace
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 3
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog-container
        image: rengifolu/backend-blog:BUILD_NUMBER
        imagePullPolicy: Always
        ports:
          - name: app
            containerPort: 8085
            protocol: TCP
      imagePullSecrets:
      - name: <your-secret-name>
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blog-namespace
  labels:
    app: blog
spec:
  type: LoadBalancer
  ports:
    - port: 8085
  selector:
    app: blog
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: blog-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: blog-service
              servicePort: 8085