version: '2'

services:
  springboot:
    image: 'rengifolu/backend-blog:latest'
    container_name: springboot
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    expose:
      - 5432



  # docker run --name postgres -e POSTGRES_PASSWORD=123 -d docker-spring-boot-postgres:latest
  # docker run -p 8080:8080 docker pull rengifolu/backend-blog:41
  # docker run --name frontend -d -p 8080:80 rengifolu/miweb:7

